### ISSUE TITLE
min max

### ISSUE THREAD

**Issue by almsam** [almsam/Numerical-Analysis-code#16]
implement a way to receive functions & confirm this works with min max

**Comment by Spunchkin** [comment]
Can you please elaborate more on what you need implemented?

**Comment by UDAYA-0504** [comment]
hii there, im intrested to work on the issue, are there anyone else working on project or can i make an effort

**Comment by almsam** [comment]
find a way to recieve functions using SymPy in order to make room for us to implement algorithms that process the functions later on

**Comment by almsam** [comment]
no worries - take your time. You have the right idea there - go ahead & implement it in a new python file & ill review the PR for ya

**Comment by UDAYA-0504** [comment]
@almsam can u add me in your project, can i make a pull request

**Comment by UDAYA-0504** [comment]
> find a way to recieve functions using SymPy in order to make room for us to implement algorithms that process the functions later on

i think we can make it out by using eval function in sympy, right?

**Comment by almsam** [comment]
>> find a way to recieve functions using SymPy in order to make room for us to implement algorithms that process the functions later on

> i think we can make it out by using eval function in sympy, right?

you should be able to in my knowledge

**Comment by almsam** [comment]
> @almsam can u add me in your project, can i make a pull request

PR's should be open to the public - let me know if it doesn't work

**Comment by UDAYA-0504** [comment]
ok thankyou

**Comment by UDAYA-0504** [comment]
hiii almsam i have created a PR, kindly check it

**Comment by almsam** [comment]
just a note on this issue: this should be in a new file & not the plotfinder, as this section is intended for code on methods like newtons method & not the regression analysis

**Comment by almsam** [comment]
see #26

**Comment by almsam** [comment]
works with #26 in pr #27 - now ill test real quick before we merge

**Comment by almsam** [comment]
merged in #27 & #28
